CREATE TABLE sessions (
  id UUID PRIMARY KEY NOT NULL,
  refresh_token VARCHAR(512) NOT NULL,
  is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITHOUT TIME ZONE
);
