// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: board_column.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoardColumn = `-- name: CreateBoardColumn :one
INSERT INTO board_column (board_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, board_id, name, position
`

type CreateBoardColumnParams struct {
	BoardID  pgtype.Int4
	Name     pgtype.Text
	Position pgtype.Int4
}

func (q *Queries) CreateBoardColumn(ctx context.Context, arg CreateBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createBoardColumn, arg.BoardID, arg.Name, arg.Position)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const deleteBoardColumn = `-- name: DeleteBoardColumn :exec
DELETE FROM board_column
WHERE id = $1
`

func (q *Queries) DeleteBoardColumn(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBoardColumn, id)
	return err
}

const getBoardColumn = `-- name: GetBoardColumn :one
SELECT id, board_id, name, position FROM board_column
WHERE id = $1
`

func (q *Queries) GetBoardColumn(ctx context.Context, id int32) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, getBoardColumn, id)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const listBoardColumns = `-- name: ListBoardColumns :many
SELECT id, board_id, name, position FROM board_column
WHERE board_id = $1
ORDER BY position
LIMIT $2
OFFSET $3
`

type ListBoardColumnsParams struct {
	BoardID pgtype.Int4
	Limit   int32
	Offset  int32
}

func (q *Queries) ListBoardColumns(ctx context.Context, arg ListBoardColumnsParams) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listBoardColumns, arg.BoardID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardColumn
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoardColumn = `-- name: UpdateBoardColumn :one
UPDATE board_column
SET name = $2, position = $3
WHERE id = $1
RETURNING id, board_id, name, position
`

type UpdateBoardColumnParams struct {
	ID       int32
	Name     pgtype.Text
	Position pgtype.Int4
}

func (q *Queries) UpdateBoardColumn(ctx context.Context, arg UpdateBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, updateBoardColumn, arg.ID, arg.Name, arg.Position)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
	)
	return i, err
}
