// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: document_content.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentContent = `-- name: CreateDocumentContent :one
INSERT INTO document_content (document_id, ydoc_state)
VALUES ($1, $2)
RETURNING document_id, ydoc_state, updated_at
`

type CreateDocumentContentParams struct {
	DocumentID pgtype.Int4
	YdocState  []byte
}

func (q *Queries) CreateDocumentContent(ctx context.Context, arg CreateDocumentContentParams) (DocumentContent, error) {
	row := q.db.QueryRow(ctx, createDocumentContent, arg.DocumentID, arg.YdocState)
	var i DocumentContent
	err := row.Scan(&i.DocumentID, &i.YdocState, &i.UpdatedAt)
	return i, err
}

const deleteDocumentContent = `-- name: DeleteDocumentContent :exec
DELETE FROM document_content
WHERE document_id = $1
`

func (q *Queries) DeleteDocumentContent(ctx context.Context, documentID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteDocumentContent, documentID)
	return err
}

const getDocumentContent = `-- name: GetDocumentContent :one
SELECT document_id, ydoc_state, updated_at FROM document_content
WHERE document_id = $1
`

func (q *Queries) GetDocumentContent(ctx context.Context, documentID pgtype.Int4) (DocumentContent, error) {
	row := q.db.QueryRow(ctx, getDocumentContent, documentID)
	var i DocumentContent
	err := row.Scan(&i.DocumentID, &i.YdocState, &i.UpdatedAt)
	return i, err
}

const updateDocumentContent = `-- name: UpdateDocumentContent :one
UPDATE document_content
SET ydoc_state = $2, updated_at = NOW()
WHERE document_id = $1
RETURNING document_id, ydoc_state, updated_at
`

type UpdateDocumentContentParams struct {
	DocumentID pgtype.Int4
	YdocState  []byte
}

func (q *Queries) UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) (DocumentContent, error) {
	row := q.db.QueryRow(ctx, updateDocumentContent, arg.DocumentID, arg.YdocState)
	var i DocumentContent
	err := row.Scan(&i.DocumentID, &i.YdocState, &i.UpdatedAt)
	return i, err
}
