// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: document.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (organization_id, title, created_by)
VALUES ($1, $2, $3)
RETURNING id, organization_id, title, created_by, created_at, updated_at
`

type CreateDocumentParams struct {
	OrganizationID pgtype.Int4
	Title          pgtype.Text
	CreatedBy      pgtype.Int4
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.OrganizationID, arg.Title, arg.CreatedBy)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, organization_id, title, created_by, created_at, updated_at FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id int32) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, organization_id, title, created_by, created_at, updated_at FROM documents
WHERE organization_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListDocumentsParams struct {
	OrganizationID pgtype.Int4
	Limit          int32
	Offset         int32
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, title, created_by, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID    int32
	Title pgtype.Text
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument, arg.ID, arg.Title)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
