// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (board_id, organization_id, user_id, document_id, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, board_id, organization_id, user_id, document_id, content, created_at
`

type CreateMessageParams struct {
	BoardID        pgtype.Int4
	OrganizationID pgtype.Int4
	UserID         pgtype.Int4
	DocumentID     pgtype.Int4
	Content        pgtype.Text
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.BoardID,
		arg.OrganizationID,
		arg.UserID,
		arg.DocumentID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.OrganizationID,
		&i.UserID,
		&i.DocumentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, board_id, organization_id, user_id, document_id, content, created_at FROM messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id int32) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.OrganizationID,
		&i.UserID,
		&i.DocumentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, board_id, organization_id, user_id, document_id, content, created_at FROM messages
WHERE board_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListMessagesParams struct {
	BoardID pgtype.Int4
	Limit   int32
	Offset  int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.BoardID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.OrganizationID,
			&i.UserID,
			&i.DocumentID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByOrganization = `-- name: ListMessagesByOrganization :many
SELECT id, board_id, organization_id, user_id, document_id, content, created_at FROM messages
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListMessagesByOrganizationParams struct {
	OrganizationID pgtype.Int4
	Limit          int32
	Offset         int32
}

func (q *Queries) ListMessagesByOrganization(ctx context.Context, arg ListMessagesByOrganizationParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.OrganizationID,
			&i.UserID,
			&i.DocumentID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET content = $2
WHERE id = $1
RETURNING id, board_id, organization_id, user_id, document_id, content, created_at
`

type UpdateMessageParams struct {
	ID      int32
	Content pgtype.Text
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.OrganizationID,
		&i.UserID,
		&i.DocumentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
