// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID             int32
	OrganizationID pgtype.Int4
	Name           pgtype.Text
	CreatedBy      pgtype.Int4
}

type BoardColumn struct {
	ID       int32
	BoardID  pgtype.Int4
	Name     pgtype.Text
	Position pgtype.Int4
}

type Document struct {
	ID             int32
	OrganizationID pgtype.Int4
	Title          pgtype.Text
	CreatedBy      pgtype.Int4
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type DocumentContent struct {
	DocumentID pgtype.Int4
	YdocState  []byte
	UpdatedAt  pgtype.Timestamp
}

type Message struct {
	ID             int32
	BoardID        pgtype.Int4
	OrganizationID pgtype.Int4
	UserID         pgtype.Int4
	DocumentID     pgtype.Int4
	Content        pgtype.Text
	CreatedAt      pgtype.Timestamp
}

type Organization struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
}

type OrganizationMember struct {
	ID             int32
	OrganizationID pgtype.Int4
	UserID         pgtype.Int4
	Role           pgtype.Text
	CreatedAt      pgtype.Timestamp
}

type Task struct {
	ID          int32
	BoardID     pgtype.Int4
	ColumnID    pgtype.Int4
	AssigneeID  pgtype.Int4
	Title       pgtype.Text
	Description pgtype.Text
	Position    pgtype.Int4
	CreatedBy   pgtype.Int4
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
