// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organization_member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateOrganizationMemberParams struct {
	OrganizationID pgtype.Int4
	UserID         pgtype.Int4
	Role           pgtype.Text
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :exec
DELETE FROM organization_members
WHERE id = $1
`

func (q *Queries) DeleteOrganizationMember(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMember, id)
	return err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE id = $1
`

func (q *Queries) GetOrganizationMember(ctx context.Context, id int32) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, id)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationMemberByOrgAndUser = `-- name: GetOrganizationMemberByOrgAndUser :one
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetOrganizationMemberByOrgAndUserParams struct {
	OrganizationID pgtype.Int4
	UserID         pgtype.Int4
}

func (q *Queries) GetOrganizationMemberByOrgAndUser(ctx context.Context, arg GetOrganizationMemberByOrgAndUserParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberByOrgAndUser, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT id, organization_id, user_id, role, created_at FROM organization_members
WHERE organization_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListOrganizationMembersParams struct {
	OrganizationID pgtype.Int4
	Limit          int32
	Offset         int32
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, arg ListOrganizationMembersParams) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationMember
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationMember = `-- name: UpdateOrganizationMember :one
UPDATE organization_members
SET role = $2
WHERE id = $1
RETURNING id, organization_id, user_id, role, created_at
`

type UpdateOrganizationMemberParams struct {
	ID   int32
	Role pgtype.Text
}

func (q *Queries) UpdateOrganizationMember(ctx context.Context, arg UpdateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMember, arg.ID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
