// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organization_invite.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationInvite = `-- name: CreateOrganizationInvite :one
INSERT INTO organization_invite (organization_id, invited_by_user_id, invited_user_id, role, status, expires_at, responded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, invited_by_user_id, invited_user_id, role, status, expires_at, created_at, responded_at
`

type CreateOrganizationInviteParams struct {
	OrganizationID  pgtype.UUID
	InvitedByUserID pgtype.UUID
	InvitedUserID   pgtype.UUID
	Role            OrganizationRole
	Status          OrganizationInviteStatus
	ExpiresAt       pgtype.Timestamp
	RespondedAt     pgtype.Timestamp
}

func (q *Queries) CreateOrganizationInvite(ctx context.Context, arg CreateOrganizationInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, createOrganizationInvite,
		arg.OrganizationID,
		arg.InvitedByUserID,
		arg.InvitedUserID,
		arg.Role,
		arg.Status,
		arg.ExpiresAt,
		arg.RespondedAt,
	)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedByUserID,
		&i.InvitedUserID,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const deleteOrganizationInvite = `-- name: DeleteOrganizationInvite :exec
DELETE FROM organization_invite
WHERE id = $1
`

func (q *Queries) DeleteOrganizationInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationInvite, id)
	return err
}

const getOrganizationInvite = `-- name: GetOrganizationInvite :one
SELECT id, organization_id, invited_by_user_id, invited_user_id, role, status, expires_at, created_at, responded_at FROM organization_invite
WHERE id = $1
`

func (q *Queries) GetOrganizationInvite(ctx context.Context, id pgtype.UUID) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, getOrganizationInvite, id)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedByUserID,
		&i.InvitedUserID,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const listOrganizationInvites = `-- name: ListOrganizationInvites :many
SELECT id, organization_id, invited_by_user_id, invited_user_id, role, status, expires_at, created_at, responded_at FROM organization_invite 
WHERE invited_user_id = $1
`

func (q *Queries) ListOrganizationInvites(ctx context.Context, invitedUserID pgtype.UUID) ([]OrganizationInvite, error) {
	rows, err := q.db.Query(ctx, listOrganizationInvites, invitedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationInvite
	for rows.Next() {
		var i OrganizationInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvitedByUserID,
			&i.InvitedUserID,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationInvite = `-- name: UpdateOrganizationInvite :one
UPDATE organization_invite
SET expires_at = $2 
WHERE id = $1
RETURNING id, organization_id, invited_by_user_id, invited_user_id, role, status, expires_at, created_at, responded_at
`

type UpdateOrganizationInviteParams struct {
	ID        pgtype.UUID
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) UpdateOrganizationInvite(ctx context.Context, arg UpdateOrganizationInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, updateOrganizationInvite, arg.ID, arg.ExpiresAt)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvitedByUserID,
		&i.InvitedUserID,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}
