// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: session.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSesion = `-- name: CreateSesion :one
INSERT INTO sessions (user_id, refresh_token, is_revoked, expires_at)
VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, refresh_token, is_revoked, created_at, expires_at
`

type CreateSesionParams struct {
	UserID       pgtype.UUID
	RefreshToken string
	IsRevoked    bool
	ExpiresAt    pgtype.Timestamp
}

func (q *Queries) CreateSesion(ctx context.Context, arg CreateSesionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSesion,
		arg.UserID,
		arg.RefreshToken,
		arg.IsRevoked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token, is_revoked, created_at, expires_at FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, refresh_token, is_revoked, created_at, expires_at FROM sessions
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListSessionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshToken,
			&i.IsRevoked,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET is_revoked = true
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET is_revoked = $2, expires_at = $3
WHERE id = $1
RETURNING id, user_id, refresh_token, is_revoked, created_at, expires_at
`

type UpdateSessionParams struct {
	ID        pgtype.UUID
	IsRevoked bool
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession, arg.ID, arg.IsRevoked, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
