// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (board_id, column_id, assignee_id, title, description, position, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, board_id, column_id, assignee_id, title, description, position, created_by, created_at
`

type CreateTaskParams struct {
	BoardID     pgtype.Int4
	ColumnID    pgtype.Int4
	AssigneeID  pgtype.Int4
	Title       pgtype.Text
	Description pgtype.Text
	Position    pgtype.Int4
	CreatedBy   pgtype.Int4
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.BoardID,
		arg.ColumnID,
		arg.AssigneeID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, board_id, column_id, assignee_id, title, description, position, created_by, created_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, board_id, column_id, assignee_id, title, description, position, created_by, created_at FROM tasks
WHERE board_id = $1
ORDER BY position
LIMIT $2
OFFSET $3
`

type ListTasksParams struct {
	BoardID pgtype.Int4
	Limit   int32
	Offset  int32
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.BoardID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByColumn = `-- name: ListTasksByColumn :many
SELECT id, board_id, column_id, assignee_id, title, description, position, created_by, created_at FROM tasks
WHERE column_id = $1
ORDER BY position
LIMIT $2
OFFSET $3
`

type ListTasksByColumnParams struct {
	ColumnID pgtype.Int4
	Limit    int32
	Offset   int32
}

func (q *Queries) ListTasksByColumn(ctx context.Context, arg ListTasksByColumnParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByColumn, arg.ColumnID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET column_id = $2, assignee_id = $3, title = $4, description = $5, position = $6
WHERE id = $1
RETURNING id, board_id, column_id, assignee_id, title, description, position, created_by, created_at
`

type UpdateTaskParams struct {
	ID          int32
	ColumnID    pgtype.Int4
	AssigneeID  pgtype.Int4
	Title       pgtype.Text
	Description pgtype.Text
	Position    pgtype.Int4
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.ColumnID,
		arg.AssigneeID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
